# Configuration file to test all helper functions
---

# .............................................................................
- set_suptitle: {}
- set_suptitle:
    title: foo
    margin: 0.02
- set_suptitle:
    title: foo
    invalid_param: 123
  _raises: true
  _match: has no property 'invalid_param'

# .............................................................................
- set_figlegend: {}
- set_figlegend:
    gather_from_fig: true
    title: foo
- set_figlegend:
    hiding_threshold: 10

# .............................................................................
# .............................................................................
- set_title: {}
- set_title:
    title: foo
- set_title:
    title: foo
    invalid_param: 123
  _raises: true
  _match: has no property 'invalid_param'

# .............................................................................
- set_labels: {}
- set_labels:
    x: foo
    y:
      label: bar
      fontsize: 20
- set_labels:
    x: foo
    y:
      label: bar
      fontsize: 20
    only_label_outer: true
- set_labels:
    x: foo
    y:
      label: bar
      invalid_param: 123
  _raises: AttributeError
  _match: has no property 'invalid_param'

# .............................................................................
- set_limits: {}
- set_limits:
    x: [~, ~]
    y: [23, 42]
- set_limits:
    x: [~, 42]
    y: [23, ~]
- set_limits:
    x:
      lower: 23
    y:
      upper: 42
- set_limits:
    x: {}
    y:
      lower: ~
      upper: 42
- set_limits:
    x: [min, max]
    y: [min, ~]
  _plot_values: [1,2,3]
- set_limits:
    x: [min, 10.]
    y: [~, min]
  _plot_values: [1,2,3]
- set_limits:
    x: [min, max]
    y: [max, min]
  _plot_values: [1,2,3]
- set_limits:
    x: [1,2,3]
  _raises: ValueError
  _match: too many values to unpack
- set_limits:
    x: foo
  _raises: ValueError
  _match: too many values to unpack
- set_limits:
    x: FB
  _raises: ValueError
  _match: Got an invalid str-type argument 'F' to the set_limits helper
- set_limits:
    x:
      invalid_key: foo
  _raises: ValueError
  _match: There are invalid keys present in a dict-type argument to set_limits!
- set_limits:
    x: [min, ~]
  _raises: ValueError
  _match: Could not get a finite value from the axis data to use for setting
- set_limits:
    x: [foo, ~]
  _raises: ValueError
  _match: Got an invalid str-type argument 'foo' to the set_limits helper

# .............................................................................
- &set_legend_defaults
  set_legend: {}
  _plot_values: [1, 2, 3]
  _plot_kwargs: {label: foobar}
- <<: *set_legend_defaults
  set_legend:
    use_legend: false
- <<: *set_legend_defaults
  set_legend:
    custom_labels: [foo, bar, baz]
- <<: *set_legend_defaults
  set_legend:
    hiding_threshold: 0
- <<: *set_legend_defaults
  set_legend: {}
  _plot_kwargs: {label: ~}
- <<: *set_legend_defaults
  set_legend: {}
  _invoke_legend: true
  _invoke_figlegend: true
- <<: *set_legend_defaults
  set_legend:
    use_legend: true
    use_figlegend: true
- <<: *set_legend_defaults
  set_legend:
    use_legend: false
    use_figlegend: true
- <<: *set_legend_defaults
  set_legend:
    invalid_param: 123
  _raises: TypeError
  _match: got an unexpected keyword argument 'invalid_param'

# .............................................................................
- set_texts:
    texts:
      - x: 0
        y: 0
        s: some_text
      - x: 1
        y: 1
        s: some_other_text
- set_texts:
    texts:
      - x: 0
        y: 0
        s: some_text
        invalid_params: 123
  _raises: AttributeError
  _match: object has no property 'invalid_params'
- set_texts:
    texts:
      - missing_argument: 123
  _raises: TypeError
  _match: missing

# .............................................................................
- annotate:
    annotations:
      - xy: [0, 1]
        text: some_text
      - xy: [10, -20.]
        text: some_other_text
      - xy: [0, 0]
        xycoords: data
        text: this is zero
        xytext: [0.1, 0.1]
        textcoords: data
        arrowprops:
          facecolor: black
          shrink: 0.05
- annotate:
    annotations:
      - xy: [0, 1]
        text: some_text
        invalid_params: 123
  _raises: AttributeError
  _match: object has no property 'invalid_params'
- annotate:
    annotations:
      - missing_argument: 123
  _raises: TypeError
  _match: missing

# .............................................................................
- set_hv_lines: {}
- set_hv_lines:
    hlines: [1,2,3]
    vlines: []
- set_hv_lines:
    hlines:
      - 1.23
      - pos: 123
    vlines:
      - 1.23
      - pos: 123
      - pos: 12.3
        limits: [.12, .3]
      - pos: 12.3
        limits: [.12, .3]
        linewidth: 10.
- set_hv_lines:
    hlines: [something_invalid, 123]
  _raises: ValueError
  _match: Got non-numeric value

# .............................................................................
- set_scales: {}
- set_scales:
    x: linear
    y: log
- set_scales:
    x:
      scale: linear
    y:
      scale: log

# .............................................................................
- set_ticks: {}
- set_ticks:
    x:
      major: [0, 3, 6]
    y:
      minor: [0, 3, 6]
- set_ticks:
    x:
      major:
        locs: [0, 3, 6]
      minor:
        locs: [0.5, 3.5, 6.5]
    y:
      major:
        locs: [0, 3, 6]
- set_ticks:
    x:
      major:
        locs: [0, 3, 6]
        labels: ['FIRST', 'SECOND', 'THIRD']
        color: g
      minor:
        locs: [1.5, 4.5, 7.5]
        labels: ['first', 'second', 'third']
        rotation: vertical
- set_ticks:
    y:
      minor:
        locs: [0, 3, 6]
        labels: ['first', 'second', 'third']
- set_ticks:
    x:
      major:
        labels: ['first', 'second', 'third']
  _raises: ValueError
  _match: Labels can only be set


# .............................................................................
- set_tick_locators:
    x:
      minor:
        name: LinearLocator
        numticks: 6
- set_tick_locators:
    y:
      major:
        name: LinearLocator
        args: [6]
- set_tick_locators:
    y:
      minor:
        name: IndexLocator
        base: 0.5
        offset: 0.25
- set_tick_locators:
    x:
      major:
        name: MaxNLocator
        nbins: 6
        integer: true
        min_n_ticks: 3
    y:
      major:
        name: MultipleLocator
        base: 2.5
- set_tick_locators:
    x:
      major:
        name: wrong_name
  _raises: AttributeError
  _match: The given locator name
- set_tick_locators:
    x:
      minor:
        name: MaxNLocator
        args: [bad, argument, list]
  _raises: ValueError
  _match: Failed setting minor locator


# .............................................................................
- set_tick_formatters:
    y:
      minor:
        name: ScalarFormatter
- set_tick_formatters:
    x:
      minor:
        name: PercentFormatter
        xmax: 5
- set_tick_formatters:
    y:
      minor:
        name: PercentFormatter
        args: [5]
- set_tick_formatters:
    x:
      major:
        name: FormatStrFormatter
        args: [">%d<"]
    y:
      major:
        name: StrMethodFormatter
        args: ['{x:.3g}']
      minor:
        name: StrMethodFormatter
        args: ['{x:.3g}']
- set_tick_formatters:
    x:
      major:
        name: wrong_name
  _raises: AttributeError
  _match: The given formatter name
- set_tick_formatters:
    x:
      major:
        name: ScalarFormatter
        bad_argument: bad
  _raises: ValueError
  _match: Failed setting major formatter


# .............................................................................
- despine: {}
- despine:
    left: true
    bottom: true
- despine:
    offset: 5
    trim: true
- despine:
    fig: foo
  _raises: ValueError
  _match: Got unexpected `fig` argument!


# .............................................................................
- invoke_functions:
    functions:
      - function: plt.plot
        args: [[1,2]]
      - function: [matplotlib, pyplot.plot]  # imported
        args: [[2,3,2,3]]
        linestyle: "--"

- invoke_functions:
    functions:
      - function: some_bad_function_name
  _raises: ValueError
  _match: could not be found

- invoke_functions:
    functions:
      - function: plt.plot
        args: [[1,2]]
        some_bad_argument: foo
  _raises: Exception
  _match: has no property 'some_bad_argument'  # from plt.plot call
